### ISSUE TITLE
not work with shadowsocks-libev

### ISSUE THREAD

**Issue by Margular** [net-reflow/reflow#9]
if connect to shadowsocks directly using chrome, it works, but if using this config, not work

```
egress privacyproxy = socks5 127.0.0.1:1080

relay {
 rule=mytrafficrule
 listen=socks5 127.0.0.1:1081
 resolver=udp 1.1.1.1:53
}

rule mytrafficrule= any[
    cond domain {
      secret-sites => privacyproxy
      adservers => reset
    }
    direct
]
```

**Comment by Margular** [comment]
that's because the speed! I tested using:
export http_proxy=socks5://127.0.0.1:1081
export https_proxy=$http_proxy
curl www.google.com > test.html

the test.html can be downloaded correctly, but it costs too much time! so the connection will be timeout in the last case. Why the tcp reflow working so slowly?

**Comment by 1var0** [comment]
> that's because the speed! I tested using:
> export http_proxy=socks5://127.0.0.1:1081
> export https_proxy=$http_proxy
> curl [www.google.com](http://www.google.com) > test.html
> 
> the test.html can be downloaded correctly, but it costs too much time! so the connection will be timeout in the last case. Why the tcp reflow working so slowly?

@Margular so you have confiugured  www.google.com as one of `secret-sites`, right?

when you use reflow as a socks server, there are two steps: first it does dns resolution using udp 1.1.1.1:53, second it makes the tcp connection
when you just use 127.0.0.1:1080, the default maybe to do dns resolution remotely, that is, the domain name is sent to the proxy
have you tested the speed of the dns separately, for example, with `dig @1.1.1.1 www.google.com`?
does `curl -x socks5h://127.0.0.1:1081` and `curl -x socks5://127.0.0.1:1081` act differently? `-x` tells curl to use a proxy, `socks5h` makes curl do dns resolution remotely, otherwise it's resolved locally.
there's also a `Proxy DNS when using SOCKS v5` option in the proxy settings of firefox you can experiment with
by the way, you can use a dns server through a proxy with something like `resolver=privacyproxy|udp 1.1.1.1:53`

**Comment by Margular** [comment]
ERROR reflow::relay: Resolver config in relay doesn't support proxy yet

if I set resolver=privacyproxy|udp 1.1.1.1:53

**Comment by 1var0** [comment]
@Margular could you provide more details? for example, have you tested dns resolution separately? is dns resolution done before or after sending a proxy request to the socks port?
